### PR TITLE
Set CeloDEX fee to 0.2%

### PR DESCRIPTION
**Pull request by diwu1989**
See https://github.com/polydex-fi/polydex-swap-core/blob/main/contracts/PolydexPair.sol#L180-L181
https://polydex.medium.com/introducing-polydex-6298cd17fb42

### CODE REVIEW

**Comment by zviadm** [comment]
I have tried this before and 0.998 is throwing errors. I don't think they have deployed same contracts to Celo as they have on Polygon. Unfortunately contracts aren't verified so we cant tell what they have deployed. 

Setting it to 0.998 causes errors, you can test using cli:

> yarn ts-node ./src/cli/cli.ts --input CELO --output cUSD --registries celodex --amount 1 --max-slippage 0.999999

**Comment by diwu1989** [comment]
Deployed contracts not source verified feels like a huge red flag if they're also not using the same fee rates.
Who knows what other modifications were made to the CeloDEX version...

**Comment by sfc-gh-dwu** [comment]
I tried to talk to the CeloDEX people asking about what fee percentage, and asking them to verify their deployed contracts.

They're clueless AF and don't even know what contract verification is, either straight up playing dumb, or trying to hide something.

**Comment by diwu1989** [comment]
I tried to talk to the CeloDEX people on discord about the fee percentage, and asking them to verify their deployed contracts.

They're clueless and don't even know what contract verification is, either straight up playing dumb, or trying to hide something.

**Comment by zviadm** [comment]
> I tried to talk to the CeloDEX people on discord about the fee percentage, and asking them to verify their deployed contracts.
> 
> They're clueless and don't even know what contract verification is, either straight up playing dumb, or trying to hide something.

Yeah, I wouldnt provide liquidity to a pool that doesnt have contract verified. But it should still be more or less safe for swapping since output is always checked in swappa router at the end.

**Pull request closed without merging**
